// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.
//
// To add a suppression to this file, right-click the message in the 
// Error List, point to "Suppress Message(s)", and click 
// "In Project Suppression File".
// You do not need to add suppressions to this file manually.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope = "member", Target = "Iata.IS.Business.Common.IReferenceManager.#GetActiveAttachmentServer()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1815:OverrideEqualsAndOperatorEqualsOnValueTypes", Scope = "type", Target = "Iata.IS.Business.ErrorCodes")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1815:OverrideEqualsAndOperatorEqualsOnValueTypes", Scope = "type", Target = "Iata.IS.Business.SamplingErrorCodes")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1815:OverrideEqualsAndOperatorEqualsOnValueTypes", Scope = "type", Target = "Iata.IS.Business.MemberProfile.EmailInfo")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope = "member", Target = "Iata.IS.Business.MemberProfile.IMemberManager.#GetAllContactTypes()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope = "member", Target = "Iata.IS.Business.MemberProfile.IMemberManager.#GetAllowedFileExtentions()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "CId", Scope = "member", Target = "Iata.IS.Business.Pax.ISamplingFormCManager.#DeleteSamplingFormC(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "CId", Scope = "member", Target = "Iata.IS.Business.Pax.ISamplingFormCManager.#GetSamplingFormCDetails(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "CId", Scope = "member", Target = "Iata.IS.Business.Pax.ISamplingFormCManager.#GetSamplingFormCRecordList(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "CId", Scope = "member", Target = "Iata.IS.Business.Pax.ISamplingFormCManager.#GetSamplingFormCSourceCodeTotal(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "CId", Scope = "member", Target = "Iata.IS.Business.Pax.ISamplingFormCManager.#SubmitSamplingFormC(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "CId", Scope = "member", Target = "Iata.IS.Business.Pax.ISamplingFormCManager.#ValidateSamplingFormC(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "DId", Scope = "member", Target = "Iata.IS.Business.Pax.ISamplingFormDEManager.#DeleteSamplingFormD(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "DId", Scope = "member", Target = "Iata.IS.Business.Pax.ISamplingFormDEManager.#GetSamplingFormD(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "DId", Scope = "member", Target = "Iata.IS.Business.Pax.ISamplingFormDEManager.#IsDuplicateSamplingFormDAttachmentFileName(System.String,System.Guid)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1040:AvoidEmptyInterfaces", Scope = "type", Target = "Iata.IS.Business.MiscUatp.IUatpInvoiceManager")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", MessageId = "Mdd", Scope = "resource", Target = "Iata.IS.Business.Messages.resources")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", MessageId = "yy", Scope = "resource", Target = "Iata.IS.Business.Messages.resources")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "Iata.IS.Business.MemberProfile.Impl.AuditProcessor`1.#ProcessAuditEntries(System.Int32,Iata.IS.Model.MemberProfile.Enums.ActionType,Iata.IS.Model.MemberProfile.Enums.ElementGroupType,!0,!0,System.Int32,System.Collections.Generic.List`1<Iata.IS.Model.MemberProfile.FutureUpdates>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1720:IdentifiersShouldNotContainTypeNames", MessageId = "string", Scope = "member", Target = "Iata.IS.Business.Reports.IProcessingDashboardManager.#IncrementBillingPeriodForInvoicesWithinFile(System.String,System.Int32,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1720:IdentifiersShouldNotContainTypeNames", MessageId = "string", Scope = "member", Target = "Iata.IS.Business.Reports.IProcessingDashboardManager.#DeleteFiles(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1720:IdentifiersShouldNotContainTypeNames", MessageId = "string", Scope = "member", Target = "Iata.IS.Business.Pax.Impl.InvoiceManager.#ValidateFlightDate(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1720:IdentifiersShouldNotContainTypeNames", MessageId = "short", Scope = "member", Target = "Iata.IS.Business.MemberProfile.Impl.QueryAndDownloadDetailsManager.#GetShortPathName(System.String,System.Text.StringBuilder,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "EBilling", Scope = "member", Target = "Iata.IS.Business.MemberProfile.IMemberManager.#UpdateEBillingConfiguration(System.Int32,Iata.IS.Model.MemberProfile.EBillingConfiguration)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "eBilling", Scope = "member", Target = "Iata.IS.Business.MemberProfile.IMemberManager.#UpdateEBillingConfiguration(System.Int32,Iata.IS.Model.MemberProfile.EBillingConfiguration)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "e", Scope = "member", Target = "Iata.IS.Business.MemberProfile.IMemberManager.#UpdateEBillingConfiguration(System.Int32,Iata.IS.Model.MemberProfile.EBillingConfiguration)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011:ConsiderPassingBaseTypesAsParameters", Scope = "member", Target = "Iata.IS.Business.Pax.Impl.InvoiceManager.#IsMemberMigratedForTransaction(Iata.IS.Model.Pax.PaxInvoice,Iata.IS.Model.Pax.Enums.TransactionType,System.Boolean)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity", Scope = "member", Target = "Iata.IS.Business.MemberProfile.Impl.AuditProcessor`1.#ProcessAuditEntries(System.Int32,Iata.IS.Model.MemberProfile.Enums.ActionType,Iata.IS.Model.MemberProfile.Enums.ElementGroupType,!0,!0,System.Int32,System.Collections.Generic.List`1<Iata.IS.Model.MemberProfile.FutureUpdates>)")]
