using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Iata.IS.Web.Reports.UserPermissionReport
{
    public class PermissionReportModel
    {
        
        public string Col1 { get; set; }
        public string Col2 { get; set; }
        public string Col3 { get; set; }
        public string Col4 { get; set; }
        public string Col5 { get; set; }
        public string Col6 { get; set; }
        public string Col7 { get; set; }
        public string Col8 { get; set; }
        public string Col9 { get; set; }
        public string Col10 { get; set; }
        public string Col11 { get; set; }
        public string Col12 { get; set; }
        public string Col13 { get; set; }
        public string Col14 { get; set; }
        public string Col15 { get; set; }
        public string Col16 { get; set; }
        public string Col17 { get; set; }
        public string Col18 { get; set; }
        public string Col19 { get; set; }
        public string Col20 { get; set; }
        public string Col21 { get; set; }
        public string Col22 { get; set; }
        public string Col23 { get; set; }
        public string Col24 { get; set; }
        public string Col25 { get; set; }
        public string Col26 { get; set; }
        public string Col27 { get; set; }
        public string Col28 { get; set; }
        public string Col29 { get; set; }
        public string Col30 { get; set; }
        public string Col31 { get; set; }
        public string Col32 { get; set; }
        public string Col33 { get; set; }
        public string Col34 { get; set; }
        public string Col35 { get; set; }
        public string Col36 { get; set; }
        public string Col37 { get; set; }
        public string Col38 { get; set; }
        public string Col39 { get; set; }
        public string Col40 { get; set; }
        public string Col41 { get; set; }
        public string Col42 { get; set; }
        public string Col43 { get; set; }
        public string Col44 { get; set; }
        public string Col45 { get; set; }
        public string Col46 { get; set; }
        public string Col47 { get; set; }
        public string Col48 { get; set; }
        public string Col49 { get; set; }
        public string Col50 { get; set; }
        public string Col51 { get; set; }
        public string Col52 { get; set; }
        public string Col53 { get; set; }
        public string Col54 { get; set; }
        public string Col55 { get; set; }
        public string Col56 { get; set; }
        public string Col57 { get; set; }
        public string Col58 { get; set; }
        public string Col59 { get; set; }
        public string Col60 { get; set; }
        public string Col61 { get; set; }
        public string Col62 { get; set; }
        public string Col63 { get; set; }
        public string Col64 { get; set; }
        public string Col65 { get; set; }
        public string Col66 { get; set; }
        public string Col67 { get; set; }
        public string Col68 { get; set; }
        public string Col69 { get; set; }
        public string Col70 { get; set; }
        public string Col71 { get; set; }
        public string Col72 { get; set; }
        public string Col73 { get; set; }
        public string Col74 { get; set; }
        public string Col75 { get; set; }
        public string Col76 { get; set; }
        public string Col77 { get; set; }
        public string Col78 { get; set; }
        public string Col79 { get; set; }
        public string Col80 { get; set; }
        public string Col81 { get; set; }
        public string Col82 { get; set; }
        public string Col83 { get; set; }
        public string Col84 { get; set; }
        public string Col85 { get; set; }
        public string Col86 { get; set; }
        public string Col87 { get; set; }
        public string Col88 { get; set; }
        public string Col89 { get; set; }
        public string Col90 { get; set; }
        public string Col91 { get; set; }
        public string Col92 { get; set; }
        public string Col93 { get; set; }
        public string Col94 { get; set; }
        public string Col95 { get; set; }
        public string Col96 { get; set; }
        public string Col97 { get; set; }
        public string Col98 { get; set; }
        public string Col99 { get; set; }
        public string Col100 { get; set; }
        public string Col101 { get; set; }
        public string Col102 { get; set; }
        public string Col103 { get; set; }
        public string Col104 { get; set; }
        public string Col105 { get; set; }
        public string Col106 { get; set; }
        public string Col107 { get; set; }
        public string Col108 { get; set; }
        public string Col109 { get; set; }
        public string Col110 { get; set; }
        public string Col111 { get; set; }
        public string Col112 { get; set; }
        public string Col113 { get; set; }
        public string Col114 { get; set; }
        public string Col115 { get; set; }
        public string Col116 { get; set; }
        public string Col117 { get; set; }
        public string Col118 { get; set; }
        public string Col119 { get; set; }
        public string Col120 { get; set; }
        public string Col121 { get; set; }
        public string Col122 { get; set; }
        public string Col123 { get; set; }
        public string Col124 { get; set; }
        public string Col125 { get; set; }
        public string Col126 { get; set; }
        public string Col127 { get; set; }
        public string Col128 { get; set; }
        public string Col129 { get; set; }
        public string Col130 { get; set; }
        public string Col131 { get; set; }
        public string Col132 { get; set; }
        public string Col133 { get; set; }
        public string Col134 { get; set; }
        public string Col135 { get; set; }
        public string Col136 { get; set; }
        public string Col137 { get; set; }
        public string Col138 { get; set; }
        public string Col139 { get; set; }
        public string Col140 { get; set; }
        public string Col141 { get; set; }
        public string Col142 { get; set; }
        public string Col143 { get; set; }
        public string Col144 { get; set; }
        public string Col145 { get; set; }
        public string Col146 { get; set; }
        public string Col147 { get; set; }
        public string Col148 { get; set; }
        public string Col149 { get; set; }
        public string Col150 { get; set; }
        public string Col151 { get; set; }
        public string Col152 { get; set; }
        public string Col153 { get; set; }
        public string Col154 { get; set; }
        public string Col155 { get; set; }
        public string Col156 { get; set; }
        public string Col157 { get; set; }
        public string Col158 { get; set; }
        public string Col159 { get; set; }
        public string Col160 { get; set; }
        public string Col161 { get; set; }
        public string Col162 { get; set; }
        public string Col163 { get; set; }
        public string Col164 { get; set; }
        public string Col165 { get; set; }
        public string Col166 { get; set; }
        public string Col167 { get; set; }
        public string Col168 { get; set; }
        public string Col169 { get; set; }
        public string Col170 { get; set; }
        public string Col171 { get; set; }
        public string Col172 { get; set; }
        public string Col173 { get; set; }
        public string Col174 { get; set; }
        public string Col175 { get; set; }
        public string Col176 { get; set; }
        public string Col177 { get; set; }
        public string Col178 { get; set; }
        public string Col179 { get; set; }
        public string Col180 { get; set; }
        public string Col181 { get; set; }
        public string Col182 { get; set; }
        public string Col183 { get; set; }
        public string Col184 { get; set; }
        public string Col185 { get; set; }
        public string Col186 { get; set; }
        public string Col187 { get; set; }
        public string Col188 { get; set; }
        public string Col189 { get; set; }
        public string Col190 { get; set; }
        public string Col191 { get; set; }
        public string Col192 { get; set; }
        public string Col193 { get; set; }
        public string Col194 { get; set; }
        public string Col195 { get; set; }
        public string Col196 { get; set; }
        public string Col197 { get; set; }
        public string Col198 { get; set; }
        public string Col199 { get; set; }
        public string Col200 { get; set; }
        /* SCP#379446 - KAL:User Permission Report Issue
         Desc: In order to incorporate new permissions added during CMP developments, 
         below extra columns are added. */
        public string Col201 { get; set; }
        public string Col202 { get; set; }
        public string Col203 { get; set; }
        public string Col204 { get; set; }
        public string Col205 { get; set; }
        public string Col206 { get; set; }
        public string Col207 { get; set; }
        public string Col208 { get; set; }
        public string Col209 { get; set; }
        public string Col210 { get; set; }
        public string Col211 { get; set; }
        public string Col212 { get; set; }
        public string Col213 { get; set; }
        public string Col214 { get; set; }
        public string Col215 { get; set; }
        public string Col216 { get; set; }
        public string Col217 { get; set; }
        public string Col218 { get; set; }
        public string Col219 { get; set; }
        public string Col220 { get; set; }
        public string Col221 { get; set; }
        public string Col222 { get; set; }
        public string Col223 { get; set; }
        public string Col224 { get; set; }
        public string Col225 { get; set; }
        public string Col226 { get; set; }
        public string Col227 { get; set; }
        public string Col228 { get; set; }
        public string Col229 { get; set; }
        public string Col230 { get; set; }
        public string Col231 { get; set; }
        public string Col232 { get; set; }
        public string Col233 { get; set; }
        public string Col234 { get; set; }
        public string Col235 { get; set; }
        public string Col236 { get; set; }
        public string Col237 { get; set; }
        public string Col238 { get; set; }
        public string Col239 { get; set; }
        public string Col240 { get; set; }
        public string Col241 { get; set; }
        public string Col242 { get; set; }
        public string Col243 { get; set; }
        public string Col244 { get; set; }
        public string Col245 { get; set; }
        public string Col246 { get; set; }
        public string Col247 { get; set; }
        public string Col248 { get; set; }
        public string Col249 { get; set; }
        public string Col250 { get; set; }
    }
}