<%@ Page Language="C#" MasterPageFile="~/Views/Shared/Anonymous.Master" Inherits="System.Web.Mvc.ViewPage<dynamic>" %>

<asp:Content ID="Content1" ContentPlaceHolderID="TitleContent" runat="server">
  ResetPasswordFailed
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">
  <h2>
    Reset Password Failed</h2>
  <p>
    This hyperlink is not valid due to one of the following reasons:
    <br />
    (i) It has expired
    <br />
    (ii) It was not generated by the system
    <br />
    (iii) It has been used by you earlier
    <br />
    (iv) A replacement hyperlink has been sent by the system
    <br />
  </p>
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="Script" runat="server">
</asp:Content>
