//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iata.IS.Web.Util {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Iata.IS.Web.Util.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing member and billed member cannot be same.
        /// </summary>
        public static string BPAXNS_10101 {
            get {
                return ResourceManager.GetString("BPAXNS.10101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected invoice type.
        /// </summary>
        public static string BPAXNS_10102 {
            get {
                return ResourceManager.GetString("BPAXNS.10102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid billing member.
        /// </summary>
        public static string BPAXNS_10103 {
            get {
                return ResourceManager.GetString("BPAXNS.10103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid billed member.
        /// </summary>
        public static string BPAXNS_10104 {
            get {
                return ResourceManager.GetString("BPAXNS.10104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid billing currency.
        /// </summary>
        public static string BPAXNS_10105 {
            get {
                return ResourceManager.GetString("BPAXNS.10105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid billing period.
        /// </summary>
        public static string BPAXNS_10106 {
            get {
                return ResourceManager.GetString("BPAXNS.10106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid settlement method.
        /// </summary>
        public static string BPAXNS_10107 {
            get {
                return ResourceManager.GetString("BPAXNS.10107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax total amount mismatch.
        /// </summary>
        public static string BPAXNS_10108 {
            get {
                return ResourceManager.GetString("BPAXNS.10108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT total amount mismatch.
        /// </summary>
        public static string BPAXNS_10109 {
            get {
                return ResourceManager.GetString("BPAXNS.10109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid &quot;From Airport&quot;.
        /// </summary>
        public static string BPAXNS_10110 {
            get {
                return ResourceManager.GetString("BPAXNS.10110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid &quot;To Airport&quot;.
        /// </summary>
        public static string BPAXNS_10111 {
            get {
                return ResourceManager.GetString("BPAXNS.10111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid listing currency.
        /// </summary>
        public static string BPAXNS_10112 {
            get {
                return ResourceManager.GetString("BPAXNS.10112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No billing member available.
        /// </summary>
        public static string BPAXNS_10113 {
            get {
                return ResourceManager.GetString("BPAXNS.10113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No transactions found.
        /// </summary>
        public static string BPAXNS_10114 {
            get {
                return ResourceManager.GetString("BPAXNS.10114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The net billing amount is invalid.
        /// </summary>
        public static string BPAXNS_10115 {
            get {
                return ResourceManager.GetString("BPAXNS.10115", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejection memo coupon breakdown not available.
        /// </summary>
        public static string BPAXNS_10116 {
            get {
                return ResourceManager.GetString("BPAXNS.10116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing memo coupon breakdown not available.
        /// </summary>
        public static string BPAXNS_10117 {
            get {
                return ResourceManager.GetString("BPAXNS.10117", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate invoice found.
        /// </summary>
        public static string BPAXNS_10118 {
            get {
                return ResourceManager.GetString("BPAXNS.10118", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid &quot;Allowed ISC&quot; amount.
        /// </summary>
        public static string BPAXNS_10119 {
            get {
                return ResourceManager.GetString("BPAXNS.10119", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid &quot;Accepted ISC&quot; amount.
        /// </summary>
        public static string BPAXNS_10120 {
            get {
                return ResourceManager.GetString("BPAXNS.10120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid &quot;Allowed UATP&quot; amount.
        /// </summary>
        public static string BPAXNS_10121 {
            get {
                return ResourceManager.GetString("BPAXNS.10121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid &quot;Allowed ISC&quot; amount.
        /// </summary>
        public static string BPAXNS_10122 {
            get {
                return ResourceManager.GetString("BPAXNS.10122", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate coupon record.
        /// </summary>
        public static string BPAXNS_10123 {
            get {
                return ResourceManager.GetString("BPAXNS.10123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Invoice .
        /// </summary>
        public static string BPAXNS_10124 {
            get {
                return ResourceManager.GetString("BPAXNS.10124", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Rejection Memo.
        /// </summary>
        public static string BPAXNS_10125 {
            get {
                return ResourceManager.GetString("BPAXNS.10125", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid amount.
        /// </summary>
        public static string BPAXNS_10126 {
            get {
                return ResourceManager.GetString("BPAXNS.10126", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Tax amount.
        /// </summary>
        public static string BPAXNS_10127 {
            get {
                return ResourceManager.GetString("BPAXNS.10127", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Flight Date.
        /// </summary>
        public static string BPAXNS_10128 {
            get {
                return ResourceManager.GetString("BPAXNS.10128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Settlement Authorization Code.
        /// </summary>
        public static string BPAXNS_10129 {
            get {
                return ResourceManager.GetString("BPAXNS.10129", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Your Rejection Number.
        /// </summary>
        public static string BPAXNS_10130 {
            get {
                return ResourceManager.GetString("BPAXNS.10130", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Memo Vat Breakdown not available.
        /// </summary>
        public static string BPAXNS_10131 {
            get {
                return ResourceManager.GetString("BPAXNS.10131", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Memo Vat Breakdown not available.
        /// </summary>
        public static string BPAXNS_10132 {
            get {
                return ResourceManager.GetString("BPAXNS.10132", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Memo Coupon Tax Breakdown not available.
        /// </summary>
        public static string BPAXNS_10133 {
            get {
                return ResourceManager.GetString("BPAXNS.10133", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Memo Coupon Vat Breakdown not available.
        /// </summary>
        public static string BPAXNS_10134 {
            get {
                return ResourceManager.GetString("BPAXNS.10134", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Invoice Status.
        /// </summary>
        public static string BPAXNS_10135 {
            get {
                return ResourceManager.GetString("BPAXNS.10135", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Memo Coupon Tax Breakdown not available.
        /// </summary>
        public static string BPAXNS_10136 {
            get {
                return ResourceManager.GetString("BPAXNS.10136", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Memo Coupon Vat Breakdown not available.
        /// </summary>
        public static string BPAXNS_10137 {
            get {
                return ResourceManager.GetString("BPAXNS.10137", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Member Location.
        /// </summary>
        public static string BPAXNS_10138 {
            get {
                return ResourceManager.GetString("BPAXNS.10138", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Rejection Memo Coupon Breakdown record.
        /// </summary>
        public static string BPAXNS_10139 {
            get {
                return ResourceManager.GetString("BPAXNS.10139", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linked Invoice not available.
        /// </summary>
        public static string BPAXNS_10140 {
            get {
                return ResourceManager.GetString("BPAXNS.10140", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Memo reference correspondence not available.
        /// </summary>
        public static string BPAXNS_10141 {
            get {
                return ResourceManager.GetString("BPAXNS.10141", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (message to be defined).
        /// </summary>
        public static string BPAXNS_10142 {
            get {
                return ResourceManager.GetString("BPAXNS.10142", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Memo reference correspondence not available.
        /// </summary>
        public static string BPAXNS_10143 {
            get {
                return ResourceManager.GetString("BPAXNS.10143", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Billing Code.
        /// </summary>
        public static string BPAXNS_10144 {
            get {
                return ResourceManager.GetString("BPAXNS.10144", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Vat amount.
        /// </summary>
        public static string BPAXNS_10145 {
            get {
                return ResourceManager.GetString("BPAXNS.10145", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Source Code.
        /// </summary>
        public static string BPAXNS_10146 {
            get {
                return ResourceManager.GetString("BPAXNS.10146", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Reason Code.
        /// </summary>
        public static string BPAXNS_10147 {
            get {
                return ResourceManager.GetString("BPAXNS.10147", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Credit Memo found..
        /// </summary>
        public static string BPAXNS_10149 {
            get {
                return ResourceManager.GetString("BPAXNS.10149", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From and To airport must be different..
        /// </summary>
        public static string BPAXNS_10150 {
            get {
                return ResourceManager.GetString("BPAXNS.10150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Invoice Number should not be current Invoice Number.
        /// </summary>
        public static string BPAXNS_10152 {
            get {
                return ResourceManager.GetString("BPAXNS.10152", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sampling Form C already exists for provisional billing airline and billing month with same lising currency in  Open/Ready for submission/Error status.
        /// </summary>
        public static string BPAXS_10101 {
            get {
                return ResourceManager.GetString("BPAXS.10101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Provisional Listing Currency.
        /// </summary>
        public static string BPAXS_10102 {
            get {
                return ResourceManager.GetString("BPAXS.10102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sampling Form C transactions not found.
        /// </summary>
        public static string BPAXS_10103 {
            get {
                return ResourceManager.GetString("BPAXS.10103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Sampling Form C record found.
        /// </summary>
        public static string BPAXS_10104 {
            get {
                return ResourceManager.GetString("BPAXS.10104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nil Form C already exists for selected member and month .
        /// </summary>
        public static string BPAXS_10105 {
            get {
                return ResourceManager.GetString("BPAXS.10105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nil Form C can not be added as Non-Nil Form C already exists for selected provisional billing member and billing month.
        /// </summary>
        public static string BPAXS_10106 {
            get {
                return ResourceManager.GetString("BPAXS.10106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sampling Form D/E transaction not found..
        /// </summary>
        public static string BPAXS_10107 {
            get {
                return ResourceManager.GetString("BPAXS.10107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Form D/E Invoice found..
        /// </summary>
        public static string BPAXS_10108 {
            get {
                return ResourceManager.GetString("BPAXS.10108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Form D Record found..
        /// </summary>
        public static string BPAXS_10109 {
            get {
                return ResourceManager.GetString("BPAXS.10109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in submission of Form C..
        /// </summary>
        public static string FormCSubmissionFailed {
            get {
                return ResourceManager.GetString("FormCSubmissionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form C submitted successfully..
        /// </summary>
        public static string FormCSubmissionSuccessful {
            get {
                return ResourceManager.GetString("FormCSubmissionSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice &quot;{0}&quot; delete failed..
        /// </summary>
        public static string InvoiceDeleteFailed {
            get {
                return ResourceManager.GetString("InvoiceDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice &quot;{0}&quot; deleted successfully..
        /// </summary>
        public static string InvoiceDeleteSuccessful {
            get {
                return ResourceManager.GetString("InvoiceDeleteSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation failed for Invoice &quot;{0}&quot;..
        /// </summary>
        public static string InvoiceValidateFailed {
            get {
                return ResourceManager.GetString("InvoiceValidateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice &quot;{0}&quot; validated successfully..
        /// </summary>
        public static string InvoiceValidateSuccessful {
            get {
                return ResourceManager.GetString("InvoiceValidateSuccessful", resourceCulture);
            }
        }
    }
}
