//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace Iata.IS.Business.ExternalInterfaces.ICHInterface.Impl
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute("ICH-Settlement", Namespace = "", IsNullable = false)]
    public partial class ICHSettlement
    {

        private string clearancePeriodField;

        private Creditor[] creditorsField;

        /// <remarks/>
        public string ClearancePeriod
        {
            get
            {
                return this.clearancePeriodField;
            }
            set
            {
                this.clearancePeriodField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public Creditor[] Creditors
        {
            get
            {
                return this.creditorsField;
            }
            set
            {
                this.creditorsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Creditor
    {
        private DebtorMemberType creditorMemberField;
        private DebtorMemberType sponsorMemberField;
        private DebtorMemberType mergeParentCreditorMemberField;

        private ZoneDetail[] zoneDetailsField;
        /// <remarks/>
        public DebtorMemberType CreditorMember
        {
            get
            {
                return this.creditorMemberField;
            }
            set
            {
                this.creditorMemberField = value;
            }
        }
        /// <remarks/>
        public DebtorMemberType CreditorSponsorMember
        {
            get
            {
                return this.sponsorMemberField;
            }
            set
            {
                this.sponsorMemberField = value;
            }
        }

        /// <remarks/>
        public DebtorMemberType MergeParentCreditorMember
        {
            get
            {
                return this.mergeParentCreditorMemberField;
            }
            set
            {
                this.mergeParentCreditorMemberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public ZoneDetail[] ZoneDetails
        {
            get
            {
                return this.zoneDetailsField;
            }
            set
            {
                this.zoneDetailsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DebtorMemberType
    {

        private string designatorField;

        private string codeField;
        /// <remarks/>
        public string Designator
        {
            get
            {
                return this.designatorField;
            }
            set
            {
                this.designatorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Total
    {

        private double localCurrencyField;

        /* SCP#390702 - KAL: Issue with Clearance Amount. Desc: Clearance Amount is made nullable. */
        private double? clearanceCurrencyField;

        /// <remarks/>
        public double LocalCurrency
        {
            get
            {
                return this.localCurrencyField;
            }
            set
            {
                this.localCurrencyField = value;
            }
        }

        /// <remarks/>
        /* SCP#390702 - KAL: Issue with Clearance Amount. Desc: Clearance Amount is made nullable. */
        public double? ClearanceCurrency
        {
            get
            {
                return this.clearanceCurrencyField;
            }
            set
            {
                this.clearanceCurrencyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InvoiceDetail
    {

        private string uniqueInvoiceNumberField;

        private DebtorMemberType transmitterMemberField;

        private string invoiceSourceField;

        private string invoiceNumberField;

        private string invoiceDateField;

        private string localCurrencyCodeField;

        private double exchangeRateField;

        private string debitOrCreditField;

        private string settlementMethodIndicatorField;

        private bool suspendedInvoiceIndicatorField;

        private bool lateSubmissionField;

        private bool isResubmittedField;

        //CMP #637: Changes to ICH Settlement 
        private string chAgreementIndicatorField;

        private string chDueDateField;

        private string salesOrderNumberField;

        private string creditorLocationIDField;
        
        private string debtorLocationIDField;

        private Total totalField;

        private System.DateTime submissionTimeField;

        /// <remarks/>
        public string UniqueInvoiceNumber
        {
            get
            {
                return this.uniqueInvoiceNumberField;
            }
            set
            {
                this.uniqueInvoiceNumberField = value;
            }
        }

        /// <remarks/>
        public DebtorMemberType TransmitterMember
        {
            get
            {
                return this.transmitterMemberField;
            }
            set
            {
                this.transmitterMemberField = value;
            }
        }

        /// <remarks/>
        public string InvoiceSource
        {
            get
            {
                return this.invoiceSourceField;
            }
            set
            {
                this.invoiceSourceField = value;
            }
        }

        /// <remarks/>
        public string InvoiceNumber
        {
            get
            {
                return this.invoiceNumberField;
            }
            set
            {
                this.invoiceNumberField = value;
            }
        }

        /// <remarks/>
        public string InvoiceDate
        {
            get
            {
                return this.invoiceDateField;
            }
            set
            {
                this.invoiceDateField = value;
            }
        }

        /// <remarks/>
        public string LocalCurrencyCode
        {
            get
            {
                return this.localCurrencyCodeField;
            }
            set
            {
                this.localCurrencyCodeField = value;
            }
        }

        /// <remarks/>
        public double ExchangeRate
        {
            get
            {
                return this.exchangeRateField;
            }
            set
            {
                this.exchangeRateField = value;
            }
        }

        /// <remarks/>
        public string DebitOrCredit
        {
            get
            {
                return this.debitOrCreditField;
            }
            set
            {
                this.debitOrCreditField = value;
            }
        }

        /// <remarks/>
        public string SettlementMethodIndicator
        {
            get
            {
                return this.settlementMethodIndicatorField;
            }
            set
            {
                this.settlementMethodIndicatorField = value;
            }
        }

        /// <remarks/>
        public bool SuspendedInvoiceIndicator
        {
            get
            {
                return this.suspendedInvoiceIndicatorField;
            }
            set
            {
                this.suspendedInvoiceIndicatorField = value;
            }
        }

        /// <remarks/>
        public bool LateSubmission
        {
            get
            {
                return this.lateSubmissionField;
            }
            set
            {
                this.lateSubmissionField = value;
            }
        }

        /// <remarks/>
        public bool IsResubmitted
        {
            get
            {
                return this.isResubmittedField;
            }
            set
            {
                this.isResubmittedField = value;
            }
        }

        //CMP #637: Changes to ICH Settlement
        /// <remarks/>
        public string CHAgreementIndicator
        {
          get
          {
            return this.chAgreementIndicatorField;
          }
          set
          {
            this.chAgreementIndicatorField = value;
          }
        }

        /// <remarks/>
        public string CHDueDate
        {
          get
          {
            return this.chDueDateField;
          }
          set
          {
            this.chDueDateField = value;
          }
        }

        /// <remarks/>
        public string SalesOrderNumber
        {
          get
          {
            return this.salesOrderNumberField;
          }
          set
          {
            this.salesOrderNumberField = value;
          }
        }

        /// <remarks/>
        public string CreditorLocationID
        {
          get
          {
            return this.creditorLocationIDField;
          }
          set
          {
            this.creditorLocationIDField = value;
          }
        }

        /// <remarks/>
        public string DebtorLocationID
        {
          get
          {
            return this.debtorLocationIDField;
          }
          set
          {
            this.debtorLocationIDField = value;
          }
        }

        /// <remarks/>
        public Total Total
        {
            get
            {
                return this.totalField;
            }
            set
            {
                this.totalField = value;
            }
        }

        /// <remarks/>
        public System.DateTime SubmissionTime
        {
            get
            {
                return this.submissionTimeField;
            }
            set
            {
                this.submissionTimeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    public enum InvoiceSource
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("IS-IDEC")]
        ISIDEC,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("IS-XML")]
        ISXML,


        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("IS-WEB")]
        ISWEB,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    public enum SettlementMethodIndicator
    {

        /// <remarks/>
        I,


        /// <remarks/>
        A,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CategoryDetail
    {

        private string billingCategoryField;

        private InvoiceDetail[] invoiceDetailsField;

        /// <remarks/>
        public string BillingCategory
        {
            get
            {
                return this.billingCategoryField;
            }
            set
            {
                this.billingCategoryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public InvoiceDetail[] InvoiceDetails
        {
            get
            {
                return this.invoiceDetailsField;
            }
            set
            {
                this.invoiceDetailsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    public enum BillingCategory
    {

        /// <remarks/>
        P,

        /// <remarks/>
        U,


        /// <remarks/>
        M,

        /// <remarks/>
        C,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DebtorDetail
    {

        private DebtorMemberType debtorMemberField;
        private DebtorMemberType sponsorMemberField;
        private DebtorMemberType mergeParentDebtorMemberField;
        private CategoryDetail[] categoryDetailsField;

        /// <remarks/>
        public DebtorMemberType DebtorMember
        {
            get
            {
                return this.debtorMemberField;
            }
            set
            {
                this.debtorMemberField = value;
            }
        }

        /// <remarks/>
        public DebtorMemberType SponsorMember
        {
            get
            {
                return this.sponsorMemberField;
            }
            set
            {
                this.sponsorMemberField = value;
            }
        }

        /// <remarks/>
        public DebtorMemberType MergeParentDebtorMember
        {
            get
            {
                return this.mergeParentDebtorMemberField;
            }
            set
            {
                this.mergeParentDebtorMemberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public CategoryDetail[] CategoryDetails
        {
            get
            {
                return this.categoryDetailsField;
            }
            set
            {
                this.categoryDetailsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZoneDetail
    {

        private string zoneCodeField;
        private string clearanceCurrencyCodeField;
        private DebtorDetail[] debtorDetailsField;

        /// <remarks/>
        public string ZoneCode
        {
            get
            {
                return this.zoneCodeField;
            }
            set
            {
                this.zoneCodeField = value;
            }
        }

        /// <remarks/>
        public string ClearanceCurrencyCode
        {
            get
            {
                return this.clearanceCurrencyCodeField;
            }
            set
            {
                this.clearanceCurrencyCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public DebtorDetail[] DebtorDetails
        {
            get
            {
                return this.debtorDetailsField;
            }
            set
            {
                this.debtorDetailsField = value;
            }
        }

        ///// <remarks/>
        //[System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        //public DebtorDetail[] CreditorDetails
        //{
        //  get
        //  {
        //    return this.debtorDetailsField;
        //  }
        //  set
        //  {
        //    this.debtorDetailsField = value;
        //  }
        //}
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    public enum ZoneCode
    {

        /// <remarks/>
        A,

        /// <remarks/>
        B,

        /// <remarks/>
        C,

        /// <remarks/>
        D,
    }
}


