//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iata.IS.Business.SISGatewayService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SISGatewayService.ISISGatewayService")]
    public interface ISISGatewayService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISISGatewayService/MemberProfileUpdate", ReplyAction="http://tempuri.org/ISISGatewayService/MemberProfileUpdateResponse")]
        string MemberProfileUpdate(string strData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISISGatewayService/BlockingRuleUpdate", ReplyAction="http://tempuri.org/ISISGatewayService/BlockingRuleUpdateResponse")]
        string BlockingRuleUpdate(string strData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISISGatewayService/InvoiceSettlement", ReplyAction="http://tempuri.org/ISISGatewayService/InvoiceSettlementResponse")]
        string InvoiceSettlement(string strData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISISGatewayService/LateSubmissionClosureNotification", ReplyAction="http://tempuri.org/ISISGatewayService/LateSubmissionClosureNotificationResponse")]
        string LateSubmissionClosureNotification(string strData);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISISGatewayServiceChannel : Iata.IS.Business.SISGatewayService.ISISGatewayService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SISGatewayServiceClient : System.ServiceModel.ClientBase<Iata.IS.Business.SISGatewayService.ISISGatewayService>, Iata.IS.Business.SISGatewayService.ISISGatewayService {
        
        public SISGatewayServiceClient() {
        }
        
        public SISGatewayServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SISGatewayServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SISGatewayServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SISGatewayServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string MemberProfileUpdate(string strData) {
            return base.Channel.MemberProfileUpdate(strData);
        }
        
        public string BlockingRuleUpdate(string strData) {
            return base.Channel.BlockingRuleUpdate(strData);
        }
        
        public string InvoiceSettlement(string strData) {
            return base.Channel.InvoiceSettlement(strData);
        }
        
        public string LateSubmissionClosureNotification(string strData) {
            return base.Channel.LateSubmissionClosureNotification(strData);
        }
    }
}
