namespace Iata.IS.Model.Enums
{
  public enum EmailTemplateId : int
  {
    FutureUpdatesEffectToChanger = 1,
    FutureUpdatesEffectToContacts = 2,
    MemberLocationUpdatedForFtpPull = 3,
    MemberLocationUpdatedWithCsv = 4,
    MemberProfileUpdates = 5,
    MemberProfileUpdatesToContacts = 6,
    CorrespondenceResponse = 7,
    InvoiceDownloadNotification = 8,
    MemberCreationToIchAchOps = 9,
    OutputGenerationNotification = 10,
    FileLateSubmission = 11,
    InvoiceLateSubmission = 12,
    ISAdminAlertMemberProfileUpdate = 13,
    ISAdminAlertBlockingRuleUpdate = 14,
    AchRecapSheetOverview = 15,
    AchRecapSheetStatus = 16,
    MemberSuspensionNotification = 17,
    ParsingValidationExceptionNotification = 18,
    SettlementFailureNotification = 19,
    XmlValidationFailureNotification = 20,
    LateSubmissionInvoiceRejectNotification = 21,
    LateSubmissionWSUnavailabilityNotification = 22,
    ValueConfirmationFailNotification = 23,
    UserWelcomeNotification = 24,
    UserChangedPasswordNotification = 25,
    FdrNotReceivedNotification = 26,
    FdrParsingAndValidationFailureNotification = 27,
    MissingSubmissionNotification = 28,
    MissingSubmissionSummary = 29,
    OutputAvailableAlert = 30,
    RechargeDataGenerationFailureNotification = 31,
    RechargeDataAvailableForDownloadNotification = 32,
    AtpcoResponseVcfNotification = 33,
    ISAdminProcessFailedNotification = 34,
    SISAdminAlertOfflineCollection = 35,
    SISAdminAlertOfflineCollectionzip = 36,
    FtpFileUploadFailure = 37,
    SISAdminAlertOutputFileGenerationPendingProcessesNotification = 38,
    OfflineOutputAvailableAlert = 39,
    SISAdminOfflineCollectionGenerationFailureAlert = 40,
    ISSubmissionDeadlineAlerts = 41,
    OutputFileAvailableAlert = 42,
    FdrExcessExchangeRatesRecievedNotification = 43,
    ValueConfirmationReportsAlerts = 44,
    ISAdminPendingBVCProcessesAlert = 45,
    SettlementDataWsUnavailabilityNotification = 46,
    MemberProfileUpdatesHtmlContents = 47,
    FutureUpdatesEffectToChangerHtmlContents = 48,
    FutureUpdatesEffectToContactsHtmlContents = 49,
    SanityCheckAlerts = 50,
    SanityCheckExceptionAlerts = 51,
    SISAdminAlertParsingAndValidationFailureNotification = 52,
    ISAdminAchRecapSheetFailureNotification = 53,
    ISAdminOldIdecFailureNotification = 54,
    iiNetFileTransferNotificationToMember =55,
    OutputFileAvailableForFormCAlert = 56,
    SISAdminOfflineCollectionDownloadFailureAlert = 57,
    CompetionofConfigurationofIchAchSpecificElement = 58,
    SuspendedInvoiceEmail=59,
    LateSubmissionInvoiceRejectHtmlContents = 60,
    SuspendedInvoiceHtmlContents = 61,
    BvcSanityCheckAlerts =62,
    BVCResponseUpdateFailed = 63,
    ISAdminNotificationForUnexpectedError = 64,
    MemberSuspendedInvoiceHtmlContents = 65,
    AutoClosingICHLateSubFailureNotification=66,
    CertificationReportNotification = 67,
    SalesForceTemplate = 68,
    SalesForceFailureTemplate = 69,
    ICHBlockingRuleUpdateNotification = 70,
    ICHBlockingRuleDeleteNotification = 71,
    ICHMemberProfileUpdateNotification = 72,
    ISAdminProcessedInvoiceCSVFailedNotification = 78,
    ICHSettlementErrorNotification = 76,
    ICHSettlementClaimFailedInvoices =74,
    ICHSettlementClaimFailedInvoicesContent =75,
    ISAdminExceptionNotification = 73,
    FutureSubmittedInvoiceInError = 77,
    LegalXmlGenerateError = 79,
      LegalXmlGenerateZipCreationFailError = 80,
      LegalXmlCreationSuccessfull = 81,
    SISAdminAlertAutoBillingWeeklyPostingFailureNotification = 82,
    AutoBillingInvoiceClosureError = 83,
    FileAvailableForDownload = 84,
    SisWebserviceErrorNotification = 85,
    CorrespondenceReportDownloadNotification = 86,
    SISAdminAlertDailyRevenueRecognitionReportGenerationFailureNotification=87,
    ISAdminPurgingTransactionFailedNotification=88,
    SISAdminAlertDailyAutoBillingIrregularityReportGenerationFailureNotification=89,
    SISAdminAlertAutoBillingIrregularityReportRegenerateStatus=90,
    LegalInvoiceArchiveRetrievalWebServiceResponseFailureAlert = 91,
    LegalInvoiceArchiveRetrievalWebServiceInitializeFailureAlert = 92,
    AutoBillingInvoiceUnavalableNotification = 93,
    AutoBillingInvoiceThreshouldValueReachedNotification = 94,
    SISAdminAlertTimeLimitFailureNotification=95,
    LegalArchiveWebServiceExceptionAlert=96,
    LegalArchiveDepositRequestFailureAlert=97,
    LegalArchiveZipFileCreationErrorAlert=98,
    SISAdminAlertUatpAtcanFailureNotification= 99,
    SISAdminAlertUatpAtcanFailureNotificationzip=100,
    UsageFileSanityCheckAlerts = 101,
    CsvUploadFileTransferred =102,
    CsvUploadFileAvailable = 103,
    LegalArchivingStatusNotification=104,
    AutoBillingIrregularityReportSLA = 105,
    IsrFileSanityCheckAlerts = 106,
    ISAdminPendingFutureSubmissionAlert = 107,
    SISAdminAlertLeadPeriodFailureNotification = 108,
    AutoBillingInvoiceClosureValidationError = 109,
    ProfileMigrationUpdateFailurNotification = 110,
    ProfileMigrationUpdateSuccessNotification = 111,
    CorrespondenceDeletedAlert = 112,
    CorrespondenceUpatedToCloseAlert = 113,
    //CMP508:Audit Trail Download with Supporting Documents
    AuditTrailPackageDownloadNotification = 114,
    //CMP529: Daily Output Generation for MISC Bilateral Invoices
    SISAdminDailyOutputProcessFailureNotification = 115,
    SISAdminDailyOutputProcessCompletionNotification = 116,
    SISAdminDailyOutputProcessPendingInvoicesNotification = 117,
    //SCP223595 FW: RM BM CM SUMMARY
    ReportDownloadNotification = 118,
    //SCP247238 - Correspondence alerts
    CorrespondeceEmailNotification = 119,
    //CMP #624: ICH Rewrite-New SMI X 
    IchSmiXWsFailureNotification = 120,

    #region CMP#608: Load Member Profile - CSV Option  

    MemberProfileCsvUploadLevel1FailureNotification = 121,
    MemberProfileCsvUploadLevel2FailureNotification = 122,
    MemberProfileCsvUploadLoadingFailureNotification = 123,
    MemberProfileCsvUploadSuccessfulNotification = 124,
    //SCP400947-SRM: Legal archiving pending for July P2
    LegalArchiveDepositeExceptionNotification = 125,

    #endregion

    //CMP #665: User Related Enhancements-FRS-v1.2 
    // [Sec 5.1: Annex 1, 2, 3, 4, 5: Email Alert when Issues are Encountered in ‘ICP New User Web Service’ or no federation id is exist of user.]
    IcpCreateUserFailNotification = 126,
    IcpEnableUserFailNotification = 127,
    IcpDisableUserFailNotification = 128,
    IcpDisableUserNoFederationIdNotification = 129,
    IcpEnableUserNoFederationIdNotification = 130,
    // SCP 413919 - Output Generation Notification - SIS Production
    MuOutputGenerationNotification = 131
  }
}
