//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace Iata.IS.Business.ExternalInterfaces.IATAInterface.Impl
{

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/XMLSchema.xsd")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://tempuri.org/XMLSchema.xsd", IsNullable = false)]
  public partial class ClearanceMonths
  {

    private string[] clearanceMonthField;

    private ClearancePeriod[] clearancePeriodsField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ClearanceMonth")]
    public string[] ClearanceMonth
    {
      get
      {
        return this.clearanceMonthField;
      }
      set
      {
        this.clearanceMonthField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
    public ClearancePeriod[] ClearancePeriods
    {
      get
      {
        return this.clearancePeriodsField;
      }
      set
      {
        this.clearancePeriodsField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/XMLSchema.xsd")]
  public partial class ClearancePeriod
  {

    private string clearancePeriodNoField;

    private MemberStatistics[] memberStatisticsField;

    /// <remarks/>
    public string ClearancePeriodNo
    {
      get
      {
        return this.clearancePeriodNoField;
      }
      set
      {
        this.clearancePeriodNoField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("MemberStatistics")]
    public MemberStatistics[] MemberStatistics
    {
      get
      {
        return this.memberStatisticsField;
      }
      set
      {
        this.memberStatisticsField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/XMLSchema.xsd")]
  public partial class MemberStatistics
  {

    private string alphaCodeField;

    private string numericCodeField;

    //CMP605 : Inclusion of new fields in Usage report and IATA recharge XML file.
    private string isMembershipStatusField;

    private string isMembershipSubStatusField;

    private Statistic[] statisticField;

    /// <remarks/>
    public string AlphaCode
    {
      get
      {
        return this.alphaCodeField;
      }
      set
      {
        this.alphaCodeField = value;
      }
    }

    /// <remarks/>
    public string NumericCode
    {
      get
      {
        return this.numericCodeField;
      }
      set
      {
        this.numericCodeField = value;
      }
    }

    //CMP605 : Inclusion of new fields in Usage report and IATA recharge XML file.
    public string ISMembershipStatus
    {
        get
        {
            return this.isMembershipStatusField;
        }
        set
        {
            this.isMembershipStatusField = value;
        }
    }

    public string ISMembershipSubStatus
    {
        get
        {
            return this.isMembershipSubStatusField;
        }
        set
        {
            this.isMembershipSubStatusField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Statistic")]
    public Statistic[] Statistic
    {
      get
      {
        return this.statisticField;
      }
      set
      {
        this.statisticField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/XMLSchema.xsd")]
  public partial class Statistic
  {

    private string iSSubmissionField;

    private string countInvoicesPAXField;

    private string countInvoicesCGOField;

    private string countInvoicesMISCField;

    private string countInvoicesUATPField;

    private string countTransactionsPAXPrimeCouponField;

    private string countTransactionsPaxBillingMemoField;

    private string countTransactionsPaxCreditMemoField;

    private string countTransactionsPaxSamplingProvisionInvoiceCouponField;

    private string countTransactionsPaxSamplingDigitEvaluationCouponField;

    private string countTransactionsPaxAutoBillingRequestField;

    private string CountTransactionsPaxValueDeterminationRequestField;

    private string countTransactionsCGOOriginalBillingAWBField;

    private string countTransactionsCGOBillingMemoField;

    private string countTransactionsCGOCreditMemoField;

    private string countTransactionsPaxRejectionMemoInclSamplingField;

    private string countTransactionsPAXSamplingUAFCouponField;

    private string countTransactionsPaxCorrespondenceField;

    private string countTransactionsCGORejectionMemoField;

    private string countTransactionsCGOCorrespondenceField;

    private string countTransactionsMISCCorrespondenceField;

    private string countTransactionsUATPCorrespondenceField;

    private string countSupportingDocumentsPAXField;

    private string countSupportingDocumentsCGOField;

    private string countSupportingDocumentsMISCField;

    private string countSupportingDocumentsUATPField;

    private string countDigitalSignatureValidationPAXsentField;

    private string countDigitalSignatureValidationCGOsentField;

    private string countDigitalSignatureValidationMISCsentField;

    private string countDigitalSignatureValidationUATPsentField;

    private string countDigitalSignatureValidationPAXrcvdField;

    private string countDigitalSignatureValidationCGOrcvdField;

    private string countDigitalSignatureValidationMISCrcvdField;

    private string countDigitalSignatureValidationUATPrcvdField;

    private string countEArchivingPAXField;

    private string countEArchivingCGOField;

    private string countEArchivingMISCField;

    private string countEArchivingUATPField;

    private string TotalSizeEArchivingPAXField;

    private string TotalSizeEArchivingCGOField;

    private string TotalSizeEArchivingMISCField;

    private string TotalSizeEArchivingUATPField;

    //CMP605 : Inclusion of new fields in Usage report and IATA recharge XML file.
    private string receivedCountInvoicesPAXField;

    private string receivedCountInvoicesCGOField;

    private string receivedCountInvoicesMISCField;

    private string receivedCountInvoicesUATPField;

    /// <remarks/>
    public string ISSubmission
    {
      get
      {
        return this.iSSubmissionField;
      }
      set
      {
        this.iSSubmissionField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
    public string CountInvoicesPAX
    {
      get
      {
        return this.countInvoicesPAXField;
      }
      set
      {
        this.countInvoicesPAXField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
    public string CountInvoicesCGO
    {
      get
      {
        return this.countInvoicesCGOField;
      }
      set
      {
        this.countInvoicesCGOField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
    public string CountInvoicesMISC
    {
      get
      {
        return this.countInvoicesMISCField;
      }
      set
      {
        this.countInvoicesMISCField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
    public string CountInvoicesUATP
    {
      get
      {
        return this.countInvoicesUATPField;
      }
      set
      {
        this.countInvoicesUATPField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
    public string CountTransactionsPAXPrimeCoupon
    {
      get
      {
        return this.countTransactionsPAXPrimeCouponField;
      }
      set
      {
        this.countTransactionsPAXPrimeCouponField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
    public string CountTransactionsPaxBillingMemo
    {
      get
      {
        return this.countTransactionsPaxBillingMemoField;
      }
      set
      {
        this.countTransactionsPaxBillingMemoField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
    public string CountTransactionsPaxCreditMemo
    {
      get
      {
        return this.countTransactionsPaxCreditMemoField;
      }
      set
      {
        this.countTransactionsPaxCreditMemoField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
    public string CountTransactionsPaxSamplingProvisionInvoiceCoupon
    {
      get
      {
        return this.countTransactionsPaxSamplingProvisionInvoiceCouponField;
      }
      set
      {
        this.countTransactionsPaxSamplingProvisionInvoiceCouponField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
    public string CountTransactionsPaxSamplingDigitEvaluationCoupon
    {
      get
      {
        return this.countTransactionsPaxSamplingDigitEvaluationCouponField;
      }
      set
      {
        this.countTransactionsPaxSamplingDigitEvaluationCouponField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
    public string CountTransactionsPaxAutoBillingRequest
    {
      get
      {
        return this.countTransactionsPaxAutoBillingRequestField;
      }
      set
      {
        this.countTransactionsPaxAutoBillingRequestField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
    public string CountTransactionsPaxValueDeterminationRequest
    {
        get
        {
            return this.CountTransactionsPaxValueDeterminationRequestField;
        }
        set
        {
            this.CountTransactionsPaxValueDeterminationRequestField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
    public string CountTransactionsCGOOriginalBillingAWB
    {
      get
      {
        return this.countTransactionsCGOOriginalBillingAWBField;
      }
      set
      {
        this.countTransactionsCGOOriginalBillingAWBField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
    public string CountTransactionsCGOBillingMemo
    {
      get
      {
        return this.countTransactionsCGOBillingMemoField;
      }
      set
      {
        this.countTransactionsCGOBillingMemoField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
    public string CountTransactionsCGOCreditMemo
    {
      get
      {
        return this.countTransactionsCGOCreditMemoField;
      }
      set
      {
        this.countTransactionsCGOCreditMemoField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
    public string CountTransactionsPaxRejectionMemoInclSampling
    {
      get
      {
        return this.countTransactionsPaxRejectionMemoInclSamplingField;
      }
      set
      {
        this.countTransactionsPaxRejectionMemoInclSamplingField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
    public string CountTransactionsPAXSamplingUAFCoupon
    {
      get
      {
        return this.countTransactionsPAXSamplingUAFCouponField;
      }
      set
      {
        this.countTransactionsPAXSamplingUAFCouponField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
    public string CountTransactionsPaxCorrespondence
    {
      get
      {
        return this.countTransactionsPaxCorrespondenceField;
      }
      set
      {
        this.countTransactionsPaxCorrespondenceField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
    public string CountTransactionsCGORejectionMemo
    {
      get
      {
        return this.countTransactionsCGORejectionMemoField;
      }
      set
      {
        this.countTransactionsCGORejectionMemoField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
    public string CountTransactionsCGOCorrespondence
    {
      get
      {
        return this.countTransactionsCGOCorrespondenceField;
      }
      set
      {
        this.countTransactionsCGOCorrespondenceField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
    public string CountTransactionsMISCCorrespondence
    {
      get
      {
        return this.countTransactionsMISCCorrespondenceField;
      }
      set
      {
        this.countTransactionsMISCCorrespondenceField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
    public string CountTransactionsUATPCorrespondence
    {
        get
        {
            return this.countTransactionsUATPCorrespondenceField;
        }
        set
        {
            this.countTransactionsUATPCorrespondenceField = value;
        }
    }
 

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
    public string CountSupportingDocumentsPAX
    {
      get
      {
        return this.countSupportingDocumentsPAXField;
      }
      set
      {
        this.countSupportingDocumentsPAXField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
    public string CountSupportingDocumentsCGO
    {
      get
      {
        return this.countSupportingDocumentsCGOField;
      }
      set
      {
        this.countSupportingDocumentsCGOField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
    public string CountSupportingDocumentsMISC
    {
      get
      {
        return this.countSupportingDocumentsMISCField;
      }
      set
      {
        this.countSupportingDocumentsMISCField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
    public string CountSupportingDocumentsUATP
    {
      get
      {
        return this.countSupportingDocumentsUATPField;
      }
      set
      {
        this.countSupportingDocumentsUATPField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
    public string CountDigitalSignatureValidationPAXsent
    {
      get
      {
        return this.countDigitalSignatureValidationPAXsentField;
      }
      set
      {
        this.countDigitalSignatureValidationPAXsentField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
    public string CountDigitalSignatureValidationCGOsent
    {
      get
      {
        return this.countDigitalSignatureValidationCGOsentField;
      }
      set
      {
        this.countDigitalSignatureValidationCGOsentField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
    public string CountDigitalSignatureValidationMISCsent
    {
      get
      {
        return this.countDigitalSignatureValidationMISCsentField;
      }
      set
      {
        this.countDigitalSignatureValidationMISCsentField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
    public string CountDigitalSignatureValidationUATPsent
    {
      get
      {
        return this.countDigitalSignatureValidationUATPsentField;
      }
      set
      {
        this.countDigitalSignatureValidationUATPsentField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
    public string CountDigitalSignatureValidationPAXrcvd
    {
      get
      {
        return this.countDigitalSignatureValidationPAXrcvdField;
      }
      set
      {
        this.countDigitalSignatureValidationPAXrcvdField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
    public string CountDigitalSignatureValidationCGOrcvd
    {
      get
      {
        return this.countDigitalSignatureValidationCGOrcvdField;
      }
      set
      {
        this.countDigitalSignatureValidationCGOrcvdField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
    public string CountDigitalSignatureValidationMISCrcvd
    {
      get
      {
        return this.countDigitalSignatureValidationMISCrcvdField;
      }
      set
      {
        this.countDigitalSignatureValidationMISCrcvdField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
    public string CountDigitalSignatureValidationUATPrcvd
    {
      get
      {
        return this.countDigitalSignatureValidationUATPrcvdField;
      }
      set
      {
        this.countDigitalSignatureValidationUATPrcvdField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
    public string CountEArchivingPAX
    {
      get
      {
        return this.countEArchivingPAXField;
      }
      set
      {
        this.countEArchivingPAXField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
    public string CountEArchivingCGO
    {
      get
      {
        return this.countEArchivingCGOField;
      }
      set
      {
        this.countEArchivingCGOField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
    public string CountEArchivingMISC
    {
      get
      {
        return this.countEArchivingMISCField;
      }
      set
      {
        this.countEArchivingMISCField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
    public string CountEArchivingUATP
    {
      get
      {
        return this.countEArchivingUATPField;
      }
      set
      {
        this.countEArchivingUATPField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
    public string TotalSizeEArchivingPAX
    {
        get
        {
            return this.TotalSizeEArchivingPAXField;
        }
        set
        {
            this.TotalSizeEArchivingPAXField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
    public string TotalSizeEArchivingCGO
    {
        get
        {
            return this.TotalSizeEArchivingCGOField;
        }
        set
        {
            this.TotalSizeEArchivingCGOField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
    public string TotalSizeEArchivingMISC
    {
        get
        {
            return this.TotalSizeEArchivingMISCField;
        }
        set
        {
            this.TotalSizeEArchivingMISCField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
    public string TotalSizeEArchivingUATP
    {
        get
        {
            return this.TotalSizeEArchivingUATPField;
        }
        set
        {
            this.TotalSizeEArchivingUATPField = value;
        }
    }

    //CMP605 : Inclusion of new fields in Usage report and IATA recharge XML file.
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
    public string ReceivedCountInvoicesPAX
    {
        get
        {
            return this.receivedCountInvoicesPAXField;
        }
        set
        {
            this.receivedCountInvoicesPAXField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
    public string ReceivedCountInvoicesCGO
    {
        get
        {
            return this.receivedCountInvoicesCGOField;
        }
        set
        {
            this.receivedCountInvoicesCGOField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
    public string ReceivedCountInvoicesMISC
    {
        get
        {
            return this.receivedCountInvoicesMISCField;
        }
        set
        {
            this.receivedCountInvoicesMISCField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
    public string ReceivedCountInvoicesUATP
    {
        get
        {
            return this.receivedCountInvoicesUATPField;
        }
        set
        {
            this.receivedCountInvoicesUATPField = value;
        }
    }
  }
}
