//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iata.IS.Web {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppSettings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppSettings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Iata.IS.Web.AppSettings", typeof(AppSettings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account creation was unsuccessful. Please correct the errors and try again..
        /// </summary>
        public static string AccountCreationUnsuccessfulMessage {
            get {
                return ResourceManager.GetString("AccountCreationUnsuccessfulMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Information.
        /// </summary>
        public static string AccountInformationText {
            get {
                return ResourceManager.GetString("AccountInformationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been deactivated. Please contact your administrator to have your account reactivated..
        /// </summary>
        public static string AccountDeactivatedMessage
        {
            get {
              return ResourceManager.GetString("AccountDeactivatedMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Your account has been locked.
        /// </summary>
        public static string AccountLockedMessage
        {
          get
          {
            return ResourceManager.GetString("AccountLockedMessage", resourceCulture);
          }
        }


        public static string MemberAccountDeactivatedMessage
        {
            get
            {
                return ResourceManager.GetString("MemberAccountDeactivatedMessage", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Account Update was unsuccessful. Please correct the errors and try again..
        /// </summary>
        public static string AccountUpdateUnsuccessfulMessage {
            get {
                return ResourceManager.GetString("AccountUpdateUnsuccessfulMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate User&apos;s Account.
        /// </summary>
        public static string ActivateUserAccountImageAltText {
            get {
                return ResourceManager.GetString("ActivateUserAccountImageAltText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/status_active.png.
        /// </summary>
        public static string ActivateUserAccountImagePath {
            get {
                return ResourceManager.GetString("ActivateUserAccountImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate Account.
        /// </summary>
        public static string ActivateUserAccountImageToolTip {
            get {
                return ResourceManager.GetString("ActivateUserAccountImageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text entered for Address 1 is an invalid format..
        /// </summary>
        public static string Address1InvalidFormatMessage1 {
            get {
                return ResourceManager.GetString("Address1InvalidFormatMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text entered for Address 1 is longer than the supported length..
        /// </summary>
        public static string Address1LengthTooLongText1 {
            get {
                return ResourceManager.GetString("Address1LengthTooLongText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address1 Requires A Value.
        /// </summary>
        public static string Address1RequiresAValue {
            get {
                return ResourceManager.GetString("Address1RequiresAValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Line 1:.
        /// </summary>
        public static string Address1Text {
            get {
                return ResourceManager.GetString("Address1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text entered for Address 2 is an invalid format..
        /// </summary>
        public static string Address2InvalidFormatMessage1 {
            get {
                return ResourceManager.GetString("Address2InvalidFormatMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text entered for Address 2 is longer than the supported length..
        /// </summary>
        public static string Address2LengthTooLongText1 {
            get {
                return ResourceManager.GetString("Address2LengthTooLongText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Line 2:.
        /// </summary>
        public static string Address2Text {
            get {
                return ResourceManager.GetString("Address2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text entered for Address 3 is an invalid format..
        /// </summary>
        public static string Address3InvalidFormatMessage1 {
            get {
                return ResourceManager.GetString("Address3InvalidFormatMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text entered for Address 3 is longer than the supported length..
        /// </summary>
        public static string Address3LengthTooLongText1 {
            get {
                return ResourceManager.GetString("Address3LengthTooLongText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Line 3:.
        /// </summary>
        public static string Address3Text {
            get {
                return ResourceManager.GetString("Address3Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to changethisemail@changethisemail.com.
        /// </summary>
        public static string AdministratorEmail {
            get {
                return ResourceManager.GetString("AdministratorEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin User Search.
        /// </summary>
        public static string AdminUserSearchText1 {
            get {
                return ResourceManager.GetString("AdminUserSearchText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer 1:.
        /// </summary>
        public static string Answer1Text {
            get {
                return ResourceManager.GetString("Answer1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer 2:.
        /// </summary>
        public static string Answer2Text {
            get {
                return ResourceManager.GetString("Answer2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer 3:.
        /// </summary>
        public static string Answer3Text {
            get {
                return ResourceManager.GetString("Answer3Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string BackText {
            get {
                return ResourceManager.GetString("BackText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Login Page.
        /// </summary>
        public static string BackToLoginPage {
            get {
                return ResourceManager.GetString("BackToLoginPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButtonText {
            get {
                return ResourceManager.GetString("CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password Failed - Invalid Old Password.
        /// </summary>
        public static string ChangePasswordFailedMessage1 {
            get {
                return ResourceManager.GetString("ChangePasswordFailedMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password Failed - New Password Must Be At Least 7 Characters In Length And Contain At Least One Alpha and One Numeric Character..
        /// </summary>
        public static string ChangePasswordFailedMessage2 {
            get {
                return ResourceManager.GetString("ChangePasswordFailedMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password Failed - New Password Already Used.
        /// </summary>
        public static string ChangePasswordFailedMessage3 {
            get {
                return ResourceManager.GetString("ChangePasswordFailedMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password Failed. Your Session Has Been Lost. Please Try Again Later..
        /// </summary>
        public static string ChangePasswordFailedMessage4 {
            get {
                return ResourceManager.GetString("ChangePasswordFailedMessage4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password Failed. Maximum Number Of Attempts Has Been Reached. Your Account Is Now Locked..
        /// </summary>
        public static string ChangePasswordFailedMessage5 {
            get {
                return ResourceManager.GetString("ChangePasswordFailedMessage5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChangePasswordFailed.
        /// </summary>
        public static string ChangePasswordFailedText1 {
            get {
                return ResourceManager.GetString("ChangePasswordFailedText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePasswordText {
            get {
                return ResourceManager.GetString("ChangePasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Security Answers.
        /// </summary>
        public static string ChangeSecurityAnswersText1 {
            get {
                return ResourceManager.GetString("ChangeSecurityAnswersText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully changed your Security Questions and Answers..
        /// </summary>
        public static string ChangeSecurityAnswerSuccess {
            get {
                return ResourceManager.GetString("ChangeSecurityAnswerSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Security Questions Failed. Your Session Has Been Lost. Please Try Again Later..
        /// </summary>
        public static string ChangeSecurityQuestionsFailedMessage1 {
            get {
                return ResourceManager.GetString("ChangeSecurityQuestionsFailedMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Security Questions Failed.  Please Try Again Later..
        /// </summary>
        public static string ChangeSecurityQuestionsFailedMessage2 {
            get {
                return ResourceManager.GetString("ChangeSecurityQuestionsFailedMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Security Questions.
        /// </summary>
        public static string ChangeSecurityQuestionsPageTitle {
            get {
                return ResourceManager.GetString("ChangeSecurityQuestionsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text entered for City Name is an invalid format..
        /// </summary>
        public static string CityNameInvalidFormatMessage1 {
            get {
                return ResourceManager.GetString("CityNameInvalidFormatMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text entered for City Name is longer than the supported length..
        /// </summary>
        public static string CityNameLengthTooLongText1 {
            get {
                return ResourceManager.GetString("CityNameLengthTooLongText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CityName Requires A Value.
        /// </summary>
        public static string CityNameRequiresAValue {
            get {
                return ResourceManager.GetString("CityNameRequiresAValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City Name:.
        /// </summary>
        public static string CityNameText {
            get {
                return ResourceManager.GetString("CityNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Here.
        /// </summary>
        public static string ClickHereText {
            get {
                return ResourceManager.GetString("ClickHereText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm New Password:.
        /// </summary>
        public static string ConfirmNewPasswordText {
            get {
                return ResourceManager.GetString("ConfirmNewPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text entered for County is an invalid format..
        /// </summary>
        public static string CountryInvalidFormatMessage1 {
            get {
                return ResourceManager.GetString("CountryInvalidFormatMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text entered for Country is longer than the supported length..
        /// </summary>
        public static string CountryLengthTooLongText1 {
            get {
                return ResourceManager.GetString("CountryLengthTooLongText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Name Requires A Value.
        /// </summary>
        public static string CountryNameRequiresAValue {
            get {
                return ResourceManager.GetString("CountryNameRequiresAValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Name:.
        /// </summary>
        public static string CountryNameText {
            get {
                return ResourceManager.GetString("CountryNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a New Account.
        /// </summary>
        public static string CreateANewAccountText {
            get {
                return ResourceManager.GetString("CreateANewAccountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your current or temporary password has expired..
        /// </summary>
        public static string CurrentOrTemporaryPasswordExpiredMessage1 {
            get {
                return ResourceManager.GetString("CurrentOrTemporaryPasswordExpiredMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password:.
        /// </summary>
        public static string CurrentPasswordText {
            get {
                return ResourceManager.GetString("CurrentPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CustomLocationIdentifier {
            get {
                return ResourceManager.GetString("CustomLocationIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database entry failed.
        /// </summary>
        public static string DatabaseEntryFailedMessage {
            get {
                return ResourceManager.GetString("DatabaseEntryFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate User&apos;s Account.
        /// </summary>
        public static string DeactivateUserAccountImageAltText {
            get {
                return ResourceManager.GetString("DeactivateUserAccountImageAltText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/status_inactive.png.
        /// </summary>
        public static string DeactivateUserAccountImagePath {
            get {
                return ResourceManager.GetString("DeactivateUserAccountImagePath", resourceCulture);
            }
        }



       public static string LocationAssociationIconPath {
            get {
                return ResourceManager.GetString("LocationAssociationIconPath", resourceCulture);
            }
        }

        public static string ProxyLoginAccountImageAltText
        {
          get
          {
            return ResourceManager.GetString("ProxyLoginAccountImageAltText", resourceCulture);
          }
        }


        public static string ProxyLoginAccountImagePath
        {
          get
          {
            return ResourceManager.GetString("ProxyLoginAccountImagePath", resourceCulture);
          }
        }


        

        /// <summary>
        ///   Looks up a localized string similar to Deactivate Account.
        /// </summary>
        public static string DeactivateUserAccountImageToolTip {
            get {
                return ResourceManager.GetString("DeactivateUserAccountImageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text entered for Department is an invalid format..
        /// </summary>
        public static string DepartmentInvalidFormatMessage1 {
            get {
                return ResourceManager.GetString("DepartmentInvalidFormatMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text entered for Department is longer than the supported length..
        /// </summary>
        public static string DepartmentLengthTooLongText1 {
            get {
                return ResourceManager.GetString("DepartmentLengthTooLongText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department:.
        /// </summary>
        public static string DepartmentText {
            get {
                return ResourceManager.GetString("DepartmentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text entered for Division is an invalid format..
        /// </summary>
        public static string DivisionInvalidFormatMessage1 {
            get {
                return ResourceManager.GetString("DivisionInvalidFormatMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text entered for Division is longer than the supported length..
        /// </summary>
        public static string DivisionLengthTooLongText1 {
            get {
                return ResourceManager.GetString("DivisionLengthTooLongText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division:.
        /// </summary>
        public static string DivisionText {
            get {
                return ResourceManager.GetString("DivisionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Security Questions.
        /// </summary>
        public static string EditSecurityQuestionsLink {
            get {
                return ResourceManager.GetString("EditSecurityQuestionsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/edit.png.
        /// </summary>
        public static string EditUserAccountImagePath {
            get {
                return ResourceManager.GetString("EditUserAccountImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditUserAccountImageToolTip {
            get {
                return ResourceManager.GetString("EditUserAccountImageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit User&apos;s Account.
        /// </summary>
        public static string EditUserImageAltText {
            get {
                return ResourceManager.GetString("EditUserImageAltText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address entered is an invalid format..
        /// </summary>
        public static string EmailAddressInvalidFormatMessage {
            get {
                return ResourceManager.GetString("EmailAddressInvalidFormatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address:.
        /// </summary>
        public static string EmailAddressText {
            get {
                return ResourceManager.GetString("EmailAddressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address entered is longer than the supported length..
        /// </summary>
        public static string EmailAddressTooLongText1 {
            get {
                return ResourceManager.GetString("EmailAddressTooLongText1", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to The email address entered is member user of any other user..
        /// </summary>
        public static string EmailAddressIsMemberUserOfOtherUser
        {
          get
          {
            return ResourceManager.GetString("EmailAddressIsMemberUserOfOtherUser", resourceCulture);
          }
        }

        /// <summary>
        ///   Looks up a localized string similar to A username for that e-mail address already exists. Please enter a different e-mail address..
        /// </summary>
        public static string EmailAlreadyExistsMessage {
            get {
                return ResourceManager.GetString("EmailAlreadyExistsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Required.
        /// </summary>
        public static string EmailRequiredMessage {
            get {
                return ResourceManager.GetString("EmailRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address Requires A Value.
        /// </summary>
        public static string EmailRequiresAValue {
            get {
                return ResourceManager.GetString("EmailRequiresAValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^[A-Za-z0-9._%+-]+@[A-Z0-9.-]+\.[A-Za-z]{2,4}$.
        /// </summary>
        public static string EmailValidation {
            get {
                return ResourceManager.GetString("EmailValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter 3 security questions that will be used in the event your password is forgotten.
        ///
        ///  All three questions are required and should be unique..
        /// </summary>
        public static string Enter3SecurityQuestionsText1 {
            get {
                return ResourceManager.GetString("Enter3SecurityQuestionsText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text entered for Fax is an invalid format..
        /// </summary>
        public static string FaxInvalidFormatMessage1 {
            get {
                return ResourceManager.GetString("FaxInvalidFormatMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text entered for Fax is longer than the supported length..
        /// </summary>
        public static string FaxLengthTooLongText1 {
            get {
                return ResourceManager.GetString("FaxLengthTooLongText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax:.
        /// </summary>
        public static string FaxText {
            get {
                return ResourceManager.GetString("FaxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        public static string FieldRequiredSymbol {
            get {
                return ResourceManager.GetString("FieldRequiredSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text entered for First Name is an invalid format..
        /// </summary>
        public static string FirstNameInvalidFormatMessage1 {
            get {
                return ResourceManager.GetString("FirstNameInvalidFormatMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text entered for First Name is longer than the supported length..
        /// </summary>
        public static string FirstNameLengthTooLongText1 {
            get {
                return ResourceManager.GetString("FirstNameLengthTooLongText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name Requires A Value.
        /// </summary>
        public static string FirstNameRequiresAValueMessage {
            get {
                return ResourceManager.GetString("FirstNameRequiresAValueMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name:.
        /// </summary>
        public static string FirstNameText {
            get {
                return ResourceManager.GetString("FirstNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password Failed. Please correct the errors and try again..
        /// </summary>
        public static string ForgotPasswordFailed {
            get {
                return ResourceManager.GetString("ForgotPasswordFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password failed to reset your password. If you have entered the wrong answer 
        ///        for the security question more times than allowed, your account may now be locked. 
        ///        &lt;br /&gt;&lt;br /&gt;
        ///        Please see your administrator if your account gets lock to have your account unlocked.
        ///    &lt;/p&gt;
        ///    &lt;p&gt;To go back to the log on screen.
        /// </summary>
        public static string ForgotPasswordFailedMessage {
            get {
                return ResourceManager.GetString("ForgotPasswordFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        public static string ForgotPasswordPageTile {
            get {
                return ResourceManager.GetString("ForgotPasswordPageTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password?.
        /// </summary>
        public static string ForgotPasswordText {
            get {
                return ResourceManager.GetString("ForgotPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please See Your Administrator To Have Your Account Unlocked..
        /// </summary>
        public static string HaveAdministratorUnlockAccountMessage1 {
            get {
                return ResourceManager.GetString("HaveAdministratorUnlockAccountMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Simplified Interline Settlement!.
        /// </summary>
        public static string HeaderMessage1 {
            get {
                return ResourceManager.GetString("HeaderMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid character in Question 1.
        /// </summary>
        public static string InvalidCharacterQuestion1 {
            get {
                return ResourceManager.GetString("InvalidCharacterQuestion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid character in Question 2.
        /// </summary>
        public static string InvalidCharacterQuestion2 {
            get {
                return ResourceManager.GetString("InvalidCharacterQuestion2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid character in Question 3.
        /// </summary>
        public static string InvalidCharacterQuestion3 {
            get {
                return ResourceManager.GetString("InvalidCharacterQuestion3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password Failed- Invalid Pass Phrase Answer.
        /// </summary>
        public static string InvalidPassPhraseAnswerMessage1 {
            get {
                return ResourceManager.GetString("InvalidPassPhraseAnswerMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Salutation.
        /// </summary>
        public static string InvalidSalutation {
            get {
                return ResourceManager.GetString("InvalidSalutation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Username. Please re-enter your Username and Try Again.
        /// </summary>
        public static string InvalidUserNameAlert {
            get {
                return ResourceManager.GetString("InvalidUserNameAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have entered an invalid username or password. If you forgot your password, click on the  &quot;Forgot Password&quot; link to reset your password.
        /// </summary>
        public static string InvalidUsernameOrPasswordEntered {
            get {
                return ResourceManager.GetString("InvalidUsernameOrPasswordEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is invalid.
        /// </summary>
        public static string InvalidWithParameter {
            get {
                return ResourceManager.GetString("InvalidWithParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text entered for Last Name is an invalid format..
        /// </summary>
        public static string LastNameInvalidFormatMessage1 {
            get {
                return ResourceManager.GetString("LastNameInvalidFormatMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text entered for Last Name is longer than the supported length..
        /// </summary>
        public static string LastNameLengthTooLongText1 {
            get {
                return ResourceManager.GetString("LastNameLengthTooLongText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name Requires A Value.
        /// </summary>
        public static string LastNameRequiresAValue {
            get {
                return ResourceManager.GetString("LastNameRequiresAValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name:.
        /// </summary>
        public static string LastNameText {
            get {
                return ResourceManager.GetString("LastNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Settings:.
        /// </summary>
        public static string LocalSettingsText {
            get {
                return ResourceManager.GetString("LocalSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location ID:.
        /// </summary>
        public static string LocationIDText {
            get {
                return ResourceManager.GetString("LocationIDText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login was unsuccessful. Please correct the errors and try again..
        /// </summary>
        public static string LoginUnsuccessfulMessage {
            get {
                return ResourceManager.GetString("LoginUnsuccessfulMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogOffProxy.
        /// </summary>
        public static string LogOffProxySuccessfulHeader {
            get {
                return ResourceManager.GetString("LogOffProxySuccessfulHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log On.
        /// </summary>
        public static string LogOnButtonText {
            get {
                return ResourceManager.GetString("LogOnButtonText", resourceCulture);
            }
        }
        
       
        
        /// <summary>
        ///   Looks up a localized string similar to 70.
        /// </summary>
        public static string MaxAddressLength {
            get {
                return ResourceManager.GetString("MaxAddressLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 250.
        /// </summary>
        public static string MaxEmailLength {
            get {
                return ResourceManager.GetString("MaxEmailLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Search Email Invalid.
        /// </summary>
        public static string MemberSearchEmailInvalid {
            get {
                return ResourceManager.GetString("MemberSearchEmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select as member..
        /// </summary>
        public static string MemberSelectionRequired {
            get {
                return ResourceManager.GetString("MemberSelectionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members:.
        /// </summary>
        public static string MembersText {
            get {
                return ResourceManager.GetString("MembersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text entered for Mobile is an invalid format..
        /// </summary>
        public static string MobileInvalidFormatMessage1 {
            get {
                return ResourceManager.GetString("MobileInvalidFormatMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text entered for Mobile is longer than the supported length..
        /// </summary>
        public static string MobileLengthTooLongText1 {
            get {
                return ResourceManager.GetString("MobileLengthTooLongText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile:.
        /// </summary>
        public static string MobileText {
            get {
                return ResourceManager.GetString("MobileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Account Success.
        /// </summary>
        public static string ModifyAccountSuccessHeader1 {
            get {
                return ResourceManager.GetString("ModifyAccountSuccessHeader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account has successfully been updated..
        /// </summary>
        public static string ModifyAccountSuccessText1 {
            get {
                return ResourceManager.GetString("ModifyAccountSuccessText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2&gt;Modify Failed&lt;/h2&gt;
        ///    &lt;p&gt;Account could not be updated. An error occured while updating your account.&lt;/p&gt;.
        /// </summary>
        public static string ModifyFailedText1 {
            get {
                return ResourceManager.GetString("ModifyFailedText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify User.
        /// </summary>
        public static string ModifyUserText {
            get {
                return ResourceManager.GetString("ModifyUserText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New passwords are required to be a minimum of 6.
        /// </summary>
        public static string NewPasswordsRequirementText1 {
            get {
                return ResourceManager.GetString("NewPasswordsRequirementText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to characters in length and contain at least one alpha and one numeric value..
        /// </summary>
        public static string NewPasswordsRequirementText2 {
            get {
                return ResourceManager.GetString("NewPasswordsRequirementText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password:.
        /// </summary>
        public static string NewPasswordText {
            get {
                return ResourceManager.GetString("NewPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string OptionActiveText1 {
            get {
                return ResourceManager.GetString("OptionActiveText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string OptionAllText1 {
            get {
                return ResourceManager.GetString("OptionAllText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InActive.
        /// </summary>
        public static string OptionInactiveText1 {
            get {
                return ResourceManager.GetString("OptionInactiveText1", resourceCulture);
            }
        }
        
                
        /// <summary>
        ///   Looks up a localized string similar to Security Questions change was unsuccessful. All three questions are required and should be unique. Please correct the errors and try again..
        /// </summary>
        public static string PasswordChangeMessage {
            get {
                return ResourceManager.GetString("PasswordChangeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password change was unsuccessful. Please correct the errors and try again..
        /// </summary>
        public static string PasswordChangeUnsuccessful {
            get {
                return ResourceManager.GetString("PasswordChangeUnsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string PasswordForLoginText {
            get {
                return ResourceManager.GetString("PasswordForLoginText", resourceCulture);
            }
        }
        
        
        
        /// <summary>
        ///   Looks up a localized string similar to The new password and confirmation password do not match..
        /// </summary>
        public static string PasswordsDoNotMatchMessage {
            get {
                return ResourceManager.GetString("PasswordsDoNotMatchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed successfully..
        /// </summary>
        public static string PasswordSuccessfullyChangedText1 {
            get {
                return ResourceManager.GetString("PasswordSuccessfullyChangedText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter an email address..
        /// </summary>
        public static string PleaseEnterAnEmailAddress {
            get {
                return ResourceManager.GetString("PleaseEnterAnEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the Pass-Phrase Answer.
        /// </summary>
        public static string PleaseEnterThePassPhraseAnswer {
            get {
                return ResourceManager.GetString("PleaseEnterThePassPhraseAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Username.
        /// </summary>
        public static string PleaseEnterUsername {
            get {
                return ResourceManager.GetString("PleaseEnterUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Try Again, if problem persists, then contact administrator.
        /// </summary>
        public static string PleaseTryAgainMessage1 {
            get {
                return ResourceManager.GetString("PleaseTryAgainMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text entered for Position Title is an invalid format..
        /// </summary>
        public static string PositionTitleInvalidFormatMessage1 {
            get {
                return ResourceManager.GetString("PositionTitleInvalidFormatMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text entered for Position Title is longer than the supported length..
        /// </summary>
        public static string PositionTitleLengthTooLongText1 {
            get {
                return ResourceManager.GetString("PositionTitleLengthTooLongText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position Title:.
        /// </summary>
        public static string PositionTitleText {
            get {
                return ResourceManager.GetString("PositionTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text entered for Postal Code is an invalid format..
        /// </summary>
        public static string PostalCodeInvalidFormatMessage1 {
            get {
                return ResourceManager.GetString("PostalCodeInvalidFormatMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text entered for Postal Code is longer than the supported length..
        /// </summary>
        public static string PostalCodeLengthTooLongText1 {
            get {
                return ResourceManager.GetString("PostalCodeLengthTooLongText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code Requires A Value.
        /// </summary>
        public static string PostalCodeRequiresAValue {
            get {
                return ResourceManager.GetString("PostalCodeRequiresAValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code:.
        /// </summary>
        public static string PostalCodeText {
            get {
                return ResourceManager.GetString("PostalCodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy As User.
        /// </summary>
        public static string ProxyAsUserText {
            get {
                return ResourceManager.GetString("ProxyAsUserText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy Login Successful.
        /// </summary>
        public static string ProxyLoginSuccessText {
            get {
                return ResourceManager.GetString("ProxyLoginSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy Login Search.
        /// </summary>
        public static string ProxyLogonSearchText {
            get {
                return ResourceManager.GetString("ProxyLogonSearchText", resourceCulture);
            }
        }
                
        /// <summary>
        ///   Looks up a localized string similar to Reset User&apos;s Password.
        /// </summary>
        public static string ResetPasswordImageAltText {
            get {
                return ResourceManager.GetString("ResetPasswordImageAltText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/resetpassword.png.
        /// </summary>
        public static string ResetPasswordImagePath {
            get {
                return ResourceManager.GetString("ResetPasswordImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string ResetPasswordImageToolTip {
            get {
                return ResourceManager.GetString("ResetPasswordImageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string RolesHeaderText {
            get {
                return ResourceManager.GetString("RolesHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salutation:.
        /// </summary>
        public static string SalutationText {
            get {
                return ResourceManager.GetString("SalutationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save User Details.
        /// </summary>
        public static string SaveUserDetailsText {
            get {
                return ResourceManager.GetString("SaveUserDetailsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Criteria.
        /// </summary>
        public static string SearchCriteriaText1 {
            get {
                return ResourceManager.GetString("SearchCriteriaText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Email Invalid.
        /// </summary>
        public static string SearchEmailInvalidMessage {
            get {
                return ResourceManager.GetString("SearchEmailInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search First Name Invalid.
        /// </summary>
        public static string SearchFirstNameInvalid {
            get {
                return ResourceManager.GetString("SearchFirstNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Last Name Invalid.
        /// </summary>
        public static string SearchLastNameInvalid {
            get {
                return ResourceManager.GetString("SearchLastNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Status Invalid.
        /// </summary>
        public static string SearchStatusInvalidMessage {
            get {
                return ResourceManager.GetString("SearchStatusInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchText {
            get {
                return ResourceManager.GetString("SearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Records Found. Please refine your search and try again..
        /// </summary>
        public static string SearchUnsuccessfulMessage {
            get {
                return ResourceManager.GetString("SearchUnsuccessfulMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security questions must be unique..
        /// </summary>
        public static string SecurityQuestionsMustBeUnique {
            get {
                return ResourceManager.GetString("SecurityQuestionsMustBeUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select One Or More Roles.
        /// </summary>
        public static string SelectOneOrMoreRolesMessage {
            get {
                return ResourceManager.GetString("SelectOneOrMoreRolesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page is under construction. For the time being, just click the submit button to continue..
        /// </summary>
        public static string SettingPageUnderConstructionMessage {
            get {
                return ResourceManager.GetString("SettingPageUnderConstructionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIS :: Log On.
        /// </summary>
        public static string SISLogOnHeader1 {
            get {
                return ResourceManager.GetString("SISLogOnHeader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIS :: Modify User.
        /// </summary>
        public static string SISModifyUserHeader1 {
            get {
                return ResourceManager.GetString("SISModifyUserHeader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIS :: Register.
        /// </summary>
        public static string SISRegisterHeader1 {
            get {
                return ResourceManager.GetString("SISRegisterHeader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text entered for SITA Address is an invalid format..
        /// </summary>
        public static string SitaAddressInvalidFormatMessage {
            get {
                return ResourceManager.GetString("SitaAddressInvalidFormatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text entered for SITA Address is longer than the supported length..
        /// </summary>
        public static string SitaAddressLengthTooLongText1 {
            get {
                return ResourceManager.GetString("SitaAddressLengthTooLongText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SITA Address:.
        /// </summary>
        public static string SitaAddressText {
            get {
                return ResourceManager.GetString("SitaAddressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify a new password of {0} or more characters..
        /// </summary>
        public static string SpecifyAPasswordOfCharacters {
            get {
                return ResourceManager.GetString("SpecifyAPasswordOfCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text entered for Staff ID is an invalid format..
        /// </summary>
        public static string StaffIDInvalidFormatMessage1 {
            get {
                return ResourceManager.GetString("StaffIDInvalidFormatMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text entered for Staff ID is longer than the supported length..
        /// </summary>
        public static string StaffIDLengthTooLongText1 {
            get {
                return ResourceManager.GetString("StaffIDLengthTooLongText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff ID:.
        /// </summary>
        public static string StaffIDText {
            get {
                return ResourceManager.GetString("StaffIDText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        public static string StatusText {
            get {
                return ResourceManager.GetString("StatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a SubDivision..
        /// </summary>
        public static string SubDivionRequiresAValue {
            get {
                return ResourceManager.GetString("SubDivionRequiresAValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text entered for Subdivision is an invalid format..
        /// </summary>
        public static string SubDivisionInvalidFormatMessage {
            get {
                return ResourceManager.GetString("SubDivisionInvalidFormatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text entered for Subdivision is longer than the supported length..
        /// </summary>
        public static string SubDivisionLengthTooLongText {
            get {
                return ResourceManager.GetString("SubDivisionLengthTooLongText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subdivision Name:.
        /// </summary>
        public static string SubdivisionNameText {
            get {
                return ResourceManager.GetString("SubdivisionNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subdivision Requires A Value.
        /// </summary>
        public static string SubDivisionRequresAValueText {
            get {
                return ResourceManager.GetString("SubDivisionRequresAValueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string SubmitText {
            get {
                return ResourceManager.GetString("SubmitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully logged out of proxy mode.
        /// </summary>
        public static string SuccessfullyLoggedOutOfProxyText1 {
            get {
                return ResourceManager.GetString("SuccessfullyLoggedOutOfProxyText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text entered for Telephone 1 is an invalid format..
        /// </summary>
        public static string Telephone1InvalidFormatMessage1 {
            get {
                return ResourceManager.GetString("Telephone1InvalidFormatMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text entered for Telephone 1 is longer than the supported length..
        /// </summary>
        public static string Telephone1LengthTooLongText1 {
            get {
                return ResourceManager.GetString("Telephone1LengthTooLongText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone1 Requires A Value.
        /// </summary>
        public static string Telephone1RequiresAValue {
            get {
                return ResourceManager.GetString("Telephone1RequiresAValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text entered for Telephone 2 is an invalid format..
        /// </summary>
        public static string Telephone2InvalidFormatMessage1 {
            get {
                return ResourceManager.GetString("Telephone2InvalidFormatMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text entered for Telephone 2 is longer than the supported length..
        /// </summary>
        public static string Telephone2LengthTooLongText1 {
            get {
                return ResourceManager.GetString("Telephone2LengthTooLongText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone 1:.
        /// </summary>
        public static string TelephoneText1 {
            get {
                return ResourceManager.GetString("TelephoneText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone 2:.
        /// </summary>
        public static string TelephoneText2 {
            get {
                return ResourceManager.GetString("TelephoneText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Zone:.
        /// </summary>
        public static string TimeZoneText {
            get {
                return ResourceManager.GetString("TimeZoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To go back to the log in,.
        /// </summary>
        public static string ToGoBackToLoginText1 {
            get {
                return ResourceManager.GetString("ToGoBackToLoginText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        public static string UserCategoryMember {
            get {
                return ResourceManager.GetString("UserCategoryMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Must Select a User Category.
        /// </summary>
        public static string UserCategoryRequired {
            get {
                return ResourceManager.GetString("UserCategoryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string UserCategorySysOps {
            get {
                return ResourceManager.GetString("UserCategorySysOps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Category:.
        /// </summary>
        public static string UserCategoryText {
            get {
                return ResourceManager.GetString("UserCategoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        public static string UsernameForLogonText {
            get {
                return ResourceManager.GetString("UsernameForLogonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the form below to modify account..
        /// </summary>
        public static string UseTheFormBelowToModifyAccountText2 {
            get {
                return ResourceManager.GetString("UseTheFormBelowToModifyAccountText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use the form below to change your password..
        /// </summary>
        public static string UseTheFormToChangePasswordText {
            get {
                return ResourceManager.GetString("UseTheFormToChangePasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the form below to create a new account.  All required fields are marked (*).
        /// </summary>
        public static string UseTheFormToCreateANewAccountPassword {
            get {
                return ResourceManager.GetString("UseTheFormToCreateANewAccountPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the form below to Search for and modify a selected user..
        /// </summary>
        public static string UseTheFormToSearchText1 {
            get {
                return ResourceManager.GetString("UseTheFormToSearchText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify a current password..
        /// </summary>
        public static string YouMustSpecifyACurrentPasswordMessage {
            get {
                return ResourceManager.GetString("YouMustSpecifyACurrentPasswordMessage", resourceCulture);
            }
        }
        
                
        /// <summary>
        ///   Looks up a localized string similar to You must specify a password.
        /// </summary>
        public static string YouMustSpecifyAPassword {
            get {
                return ResourceManager.GetString("YouMustSpecifyAPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify a username..
        /// </summary>
        public static string YouMustSpecifyAUsername {
            get {
                return ResourceManager.GetString("YouMustSpecifyAUsername", resourceCulture);
            }
        }
               


        /// <summary>
        ///   Looks up a localized string similar to Billing Month From:.
        /// </summary>
        public static string BillingMonthFrom
        {
          get
          {
            return ResourceManager.GetString("BillingMonthFrom", resourceCulture);
          }
        }

        /// <summary>
        ///   Looks up a localized string similar to Billing Month From cannot be greater than Billing Month To.
        /// </summary>
        public static string BillingMonthFromToRestriction
        {
          get
          {
            return ResourceManager.GetString("BillingMonthFromToRestriction", resourceCulture);
          }
        }

        /// <summary>
        ///   Looks up a localized string similar to Billing Month To:.
        /// </summary>
        public static string BillingMonthTo
        {
          get
          {
            return ResourceManager.GetString("BillingMonthTo", resourceCulture);
          }
        }

        /// <summary>
        ///   Looks up a localized string similar to Billing Period From:.
        /// </summary>
        public static string BillingPeriodFrom
        {
          get
          {
            return ResourceManager.GetString("BillingPeriodFrom", resourceCulture);
          }
        }

        /// <summary>
        ///   Looks up a localized string similar to Billing Period From cannot be greater than Billing Period To.
        /// </summary>
        public static string BillingPeriodFromToRestriction
        {
          get
          {
            return ResourceManager.GetString("BillingPeriodFromToRestriction", resourceCulture);
          }
        }

        /// <summary>
        ///   Looks up a localized string similar to Billing Period To:.
        /// </summary>
        public static string BillingPeriodTo
        {
          get
          {
            return ResourceManager.GetString("BillingPeriodTo", resourceCulture);
          }
        }

        /// <summary>
        ///   Looks up a localized string similar to Billing Year:.
        /// </summary>
        public static string BillingYear
        {
          get
          {
            return ResourceManager.GetString("BillingYear", resourceCulture);
          }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error in IS-Download functionality.
        /// </summary>
        public static string BillingYearExceptionString
        {
          get
          {
            return ResourceManager.GetString("BillingYearExceptionString", resourceCulture);
          }
        }

        /// <summary>
        ///   Looks up a localized string similar to 2009.
        /// </summary>
        public static string BillingYearToStartWith
        {
          get
          {
            return ResourceManager.GetString("BillingYearToStartWith", resourceCulture);
          }
        }

        /// <summary>
        ///   Looks up a localized string similar to File Type:.
        /// </summary>
        public static string FileType
        {
          get
          {
            return ResourceManager.GetString("FileType", resourceCulture);
          }
        }

        /// <summary>
        ///   Looks up a localized string similar to .ZIP.
        /// </summary>
        public static string FileTypeAccepted
        {
          get
          {
            return ResourceManager.GetString("FileTypeAccepted", resourceCulture);
          }
        }
        
      /// <summary>
        ///   Looks up a localized string similar to The file name entered does not match the required file type..
        /// </summary>
        public static string IncorrectFileType
        {
          get
          {
            return ResourceManager.GetString("IncorrectFileType", resourceCulture);
          }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save Failed.
        /// </summary>
        public static string SaveFailed
        {
          get
          {
            return ResourceManager.GetString("SaveFailed", resourceCulture);
          }
        }

        /// <summary>
        ///   Looks up a localized string similar to A file with that name allready exists in our system..
        /// </summary>
        public static string FileExistsAlready
        {
          get
          {
            return ResourceManager.GetString("FileExistsAlready", resourceCulture);
          }
        }

        /// <summary>
        ///   Looks up a localized string similar to Your file uploaded successfully and is in processing..
        /// </summary>
        public static string FileUploadSuccessful
        {
          get
          {
            return ResourceManager.GetString("FileUploadSuccessful", resourceCulture);
          }
        }

        /// <summary>
        ///   Looks up a localized string similar to Your file, named {0} was successfully uploaded and is in processing..
        /// </summary>
        public static string FileUploadSuccessfulBody
        {
          get
          {
            return ResourceManager.GetString("FileUploadSuccessfulBody", resourceCulture);
          }
        }

        /// <summary>
        ///   Looks up a localized string similar to Your file uploaded successfully and is in processing..
        /// </summary>
        public static string FileUploadSuccessfulForWeb
        {
          get
          {
            return ResourceManager.GetString("FileUploadSuccessfulForWeb", resourceCulture);
          }
        }

        /// <summary>
        ///   Looks up a localized string similar to Your file uploaded successfully and is in processing..
        /// </summary>
        public static string FileUploadSuccessfulForMemberUploadCsv
        {
            get
            {
                return ResourceManager.GetString("FileUploadSuccessfulForMemberUploadCsv", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Your file upload is unsuccessful due to internal error. Please resubmit the file.
        /// </summary>
        public static string FileUploadFailsForIsWeb
        {
          get
          {
            return ResourceManager.GetString("FileUploadFailsForIsWeb", resourceCulture);
          }
        }

        /// <summary>
        ///   Looks up a localized string similar to File you are uploading must be .zip.
        /// </summary>
        public static string ZipFileRequired
        {
          get
          {
            return ResourceManager.GetString("ZipFileRequired", resourceCulture);
          }
        }

        /// <summary>
        ///   Looks up a localized string similar to DataService.
        /// </summary>
        public static string DataServiceName
        {
          get
          {
            return ResourceManager.GetString("DataServiceName", resourceCulture);
          }
        }


        /// <summary>
        ///   Looks up a localized string similar to April.
        /// </summary>
        public static string MonthApril
        {
          get
          {
            return ResourceManager.GetString("MonthApril", resourceCulture);
          }
        }

        /// <summary>
        ///   Looks up a localized string similar to August.
        /// </summary>
        public static string MonthAugust
        {
          get
          {
            return ResourceManager.GetString("MonthAugust", resourceCulture);
          }
        }

        /// <summary>
        ///   Looks up a localized string similar to December.
        /// </summary>
        public static string MonthDecember
        {
          get
          {
            return ResourceManager.GetString("MonthDecember", resourceCulture);
          }
        }

        /// <summary>
        ///   Looks up a localized string similar to February.
        /// </summary>
        public static string MonthFebruary
        {
          get
          {
            return ResourceManager.GetString("MonthFebruary", resourceCulture);
          }
        }

        /// <summary>
        ///   Looks up a localized string similar to January.
        /// </summary>
        public static string MonthJanuary
        {
          get
          {
            return ResourceManager.GetString("MonthJanuary", resourceCulture);
          }
        }

        /// <summary>
        ///   Looks up a localized string similar to July.
        /// </summary>
        public static string MonthJuly
        {
          get
          {
            return ResourceManager.GetString("MonthJuly", resourceCulture);
          }
        }

        /// <summary>
        ///   Looks up a localized string similar to June.
        /// </summary>
        public static string MonthJune
        {
          get
          {
            return ResourceManager.GetString("MonthJune", resourceCulture);
          }
        }

        /// <summary>
        ///   Looks up a localized string similar to March.
        /// </summary>
        public static string MonthMarch
        {
          get
          {
            return ResourceManager.GetString("MonthMarch", resourceCulture);
          }
        }

        /// <summary>
        ///   Looks up a localized string similar to May.
        /// </summary>
        public static string MonthMay
        {
          get
          {
            return ResourceManager.GetString("MonthMay", resourceCulture);
          }
        }

        /// <summary>
        ///   Looks up a localized string similar to November.
        /// </summary>
        public static string MonthNovember
        {
          get
          {
            return ResourceManager.GetString("MonthNovember", resourceCulture);
          }
        }

        /// <summary>
        ///   Looks up a localized string similar to October.
        /// </summary>
        public static string MonthOctober
        {
          get
          {
            return ResourceManager.GetString("MonthOctober", resourceCulture);
          }
        }

        /// <summary>
        ///   Looks up a localized string similar to September.
        /// </summary>
        public static string MonthSeptember
        {
          get
          {
            return ResourceManager.GetString("MonthSeptember", resourceCulture);
          }
        }

        /// <summary>
        ///   Looks up a localized string similar to C:\FTPRoot\{0}\Download\.
        /// </summary>
        public static string DownloadFileMoveLocation
        {
          get
          {
            return ResourceManager.GetString("DownloadFileMoveLocation", resourceCulture);
          }
        }

        /// <summary>
        ///   Looks up a localized string similar to There was an error in the file download process. Please try again, or contact your administrator..
        /// </summary>
        public static string DownloadFileError
        {
          get
          {
            return ResourceManager.GetString("DownloadFileError", resourceCulture);
          }
        }

        /// <summary>
        ///   Looks up a localized string similar to Download File.
        /// </summary>
        public static string DownloadFileImageAltText
        {
          get
          {
            return ResourceManager.GetString("DownloadFileImageAltText", resourceCulture);
          }
        }

        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/status_active.png.
        /// </summary>
        public static string DownloadFileImagePath
        {
          get
          {
            return ResourceManager.GetString("DownloadFileImagePath", resourceCulture);
          }
        }

        /// <summary>
        ///   Looks up a localized string similar to Download File.
        /// </summary>
        public static string DownloadFileImageToolTip
        {
          get
          {
            return ResourceManager.GetString("DownloadFileImageToolTip", resourceCulture);
          }
        }

        /// <summary>
        ///   Looks up a localized string if file is empty
        /// </summary>
        public static string EmptyFile
        {
            get
            {
                return ResourceManager.GetString("EmptyFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/status_active.png.
        /// </summary>
        public static string DownloadZipFileImagePath
        {
            get
            {
                return ResourceManager.GetString("DownloadZipFileImagePath", resourceCulture);
            }
        }

        /// <summary>
        ///   
        /// </summary>
        public static string DuplicateMemberContact
        {
          get
          {
            return ResourceManager.GetString("DuplicateMemberContact", resourceCulture);
          }
        }

        /// <summary>
        ///   CMp685
        /// </summary>
        public static string UrlPasswordResetLink
        {
          get
          {
            return ResourceManager.GetString("UrlPasswordResetLink", resourceCulture);
          }
        }

        /// <summary>
        ///   CMP685
        /// </summary>
        public static string ResetPasswordSuccessMessage
        {
          get
          {
            return ResourceManager.GetString("ResetPasswordSuccessMessage", resourceCulture);
          }
        }
      

    }
}
